apiVersion: v1
kind: Secret
metadata:
  name: library-events-consumer-secret
  namespace: default
  labels:
    app: library-events-consumer
type: Opaque
stringData:                             # plain text — Kubernetes base64-encodes it automatically
  SPRING_DATASOURCE_PASSWORD: "secret"
