server:
  port: 8081

spring:
  application:
    name: library-events-consumer
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: library-events-listener-group
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: latest


