spring:
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:stage-broker1:9092,stage-broker2:9092}
    topic: library-events
    producer:
      acks: all
      retries: 15
      transaction-id-prefix: lib-events-tx-stage-
      properties:
        retry.backoff.ms: 2000
