package com.learnkafka.service;

import com.learnkafka.domain.Book;
import com.learnkafka.domain.LibraryEvent;
import com.learnkafka.domain.LibraryEventType;
import com.learnkafka.dto.BookDto;
import com.learnkafka.dto.LibraryEventDto;
import com.learnkafka.repository.BookRepository;
import com.learnkafka.repository.LibraryEventRepository;
import org.apache.kafka.clients.consumer.ConsumerRecord;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.testcontainers.context.ImportTestcontainers;
import org.springframework.boot.testcontainers.service.connection.ServiceConnection;
import org.testcontainers.containers.PostgreSQLContainer;

import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
@ImportTestcontainers
class LibraryEventServiceIntegrationTest {

    @ServiceConnection
    static PostgreSQLContainer<?> postgres = new PostgreSQLContainer<>("postgres:latest");

    @Autowired
    private LibraryEventService libraryEventService;

    @Autowired
    private LibraryEventRepository libraryEventRepository;

    @Autowired
    private BookRepository bookRepository;

    @BeforeEach
    void setUp() {
        bookRepository.deleteAll();
        libraryEventRepository.deleteAll();
    }

    @Test
    void processEvent_ADD_shouldPersistLibraryEventAndBook() {
        // given
        BookDto bookDto = new BookDto(1, "Clean Code", "Robert C. Martin");
        LibraryEventDto libraryEventDto = new LibraryEventDto(null, LibraryEventType.ADD, bookDto);
        ConsumerRecord<Integer, LibraryEventDto> consumerRecord = buildConsumerRecord(null, libraryEventDto);

        // when
        libraryEventService.processEvent(consumerRecord);

        // then
        var libraryEvents = libraryEventRepository.findAll();
        assertEquals(1, libraryEvents.size());

        LibraryEvent savedEvent = libraryEvents.getFirst();
        assertNotNull(savedEvent.getLibraryEventId());
        assertEquals(LibraryEventType.ADD, savedEvent.getEventType());

        // Verify Book was persisted
        var books = bookRepository.findAll();
        assertEquals(1, books.size());

        Book savedBook = books.getFirst();
        assertEquals(1, savedBook.getBookId());
        assertEquals("Clean Code", savedBook.getBookName());
        assertEquals("Robert C. Martin", savedBook.getBookAuthor());

        // Verify the FK relationship — Book references LibraryEvent
        assertNotNull(savedBook.getLibraryEvent());
        assertEquals(savedEvent.getLibraryEventId(), savedBook.getLibraryEvent().getLibraryEventId());
    }

    @Test
    void processEvent_ADD_shouldAutoGenerateLibraryEventId() {
        // given
        BookDto bookDto = new BookDto(42, "Effective Java", "Joshua Bloch");
        LibraryEventDto libraryEventDto = new LibraryEventDto(null, LibraryEventType.ADD, bookDto);
        ConsumerRecord<Integer, LibraryEventDto> consumerRecord = buildConsumerRecord(null, libraryEventDto);

        // when
        libraryEventService.processEvent(consumerRecord);

        // then
        var libraryEvents = libraryEventRepository.findAll();
        assertEquals(1, libraryEvents.size());

        LibraryEvent savedEvent = libraryEvents.getFirst();
        assertNotNull(savedEvent.getLibraryEventId(), "libraryEventId should be auto-generated by the DB");
    }

    @Test
    void processEvent_ADD_multipleShouldPersistMultipleRecords() {
        // given
        BookDto bookDto1 = new BookDto(1, "Clean Code", "Robert C. Martin");
        LibraryEventDto dto1 = new LibraryEventDto(null, LibraryEventType.ADD, bookDto1);

        BookDto bookDto2 = new BookDto(2, "Effective Java", "Joshua Bloch");
        LibraryEventDto dto2 = new LibraryEventDto(null, LibraryEventType.ADD, bookDto2);

        // when
        libraryEventService.processEvent(buildConsumerRecord(null, dto1));
        libraryEventService.processEvent(buildConsumerRecord(null, dto2));

        // then
        assertEquals(2, libraryEventRepository.count());
        assertEquals(2, bookRepository.count());

        Optional<Book> book1 = bookRepository.findById(1);
        assertTrue(book1.isPresent());
        assertEquals("Clean Code", book1.get().getBookName());

        Optional<Book> book2 = bookRepository.findById(2);
        assertTrue(book2.isPresent());
        assertEquals("Effective Java", book2.get().getBookName());
    }

    private ConsumerRecord<Integer, LibraryEventDto> buildConsumerRecord(Integer key, LibraryEventDto value) {
        return new ConsumerRecord<>(
                "library-events",       // topic
                0,                      // partition
                0L,                     // offset
                key,                    // key
                value                   // value
        );
    }
}


